### PR TITLE
chore lift Dependencies for node 18

### PR DESCRIPTION
**Pull request by CKY-**
this has been tested on 5.60 and 5.59.2

it builds and loads 
image

### CODE REVIEW

**Comment by Wissididom** [comment]
Since git tracks the `package-lock.json` file, shouldn't that be updated too? Also, I updated the dependencies in #2, I just need to test it again, after I've done a force push today without Firebot at hand.

**Comment by CKY-** [comment]
> Since git tracks the `package-lock.json` file, shouldn't that be updated too? Also, I updated the dependencies in #2, I just need to test it again, after I've done a force push today without Firebot at hand.

you are correct i removed it by mistake. 

this only applies to firebot 5.59 and above. 

and will crash anything lower than that

**Comment by CKY-** [comment]
@Wissididom 
I will be fixing this but i had to fix my branch. 
I looked at the #2 and you have exceeded what firebot has firebot is on node 18.17.1 so the typings from 18.17.1 need to be used firebots typescript version is 4.7.2 so the script can not be newer then what is running it..

**Comment by CKY-** [comment]
we'll be back after these messages...

**Comment by Wissididom** [comment]
I thought because the custom script gets built (to a `.js` file through webpack) separately (with `npm run build:dev` or `npm run build`), it can have whatever version I'd like, sorry.

**Pull request closed without merging**
